; General Application Settings
[General]
app_name = SepsisEvaluationPipeline
version = 0.1.0
log_level = INFO
admin_email = daniel.walke@ovgu.de

; Path Configurations
[Paths]
mimic_input_dir = D:\Datasets\mimic-iv-2.2

[PANEL]
panel_name = CBC_BMP
panels_names = CBC, CBC_BMP, HIL, EXTCBC, BMP, WBCDIFF, EXTELECT, LIVER, COAG, KIDNEY
include_sbc = True

; RANDOM SEED Configurations
[RANDOM]
seed = 42

; Imputation Configurations
[PREPROCESSING]
imputation = drop

[TRAINING]
num_workers_for_loading = 6
batch_size = 512*10
limit_neighbors = 10
max_ram_gb = 20
